apiVersion: v1
kind: Service
metadata:
  name: whoami-svc
  labels:
    app: auth-one
    component: whoami
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    component: whoami
  type: ClusterIP
