apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-dep
  labels:
    component: whoami
    app: auth-one
spec:
  replicas: 1
  selector:
    matchLabels:
      component: whoami
  template:
    metadata:
      labels:
        component: whoami
    spec:
      containers:
      - name: whoami-container
        image: dockla/auth-one-whoami:0.2.0
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80
            protocol: TCP
      restartPolicy: Always
