apiVersion: v1
kind: Service
metadata:
  name: reverse-proxy-svc
  labels:
    app: auth-one
    component: reverse-proxy
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  externalIPs:
    - 192.168.99.107 # Here you should provide the public IP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    component: reverse-proxy
