apiVersion: v1
kind: Service
metadata:
  name: home-ui-svc
  labels:
    app: auth-one
    component: home-ui
spec:
  ports:
  - port: 3200
    targetPort: 80
    protocol: TCP
  selector:
    component: home-ui
  type: ClusterIP
