apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-ui-dep
  labels:
    component: home-ui
    app: auth-one
spec:
  replicas: 1
  selector:
    matchLabels:
      component: home-ui
  template:
    metadata:
      labels:
        component: home-ui
    spec:
      containers:
      - name: home-ui-container
        image: dockla/auth-one-home-ui:0.2.0
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80
            protocol: TCP
      restartPolicy: Always
