apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: mongo-deploy
  labels:
    component: mongo
    app: auth-one
    tier: data
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      component: mongo
  template:
    metadata:
      labels:
        component: mongo
    spec:
      volumes:
      - name: mongo-storage
        persistentVolumeClaim:
          claimName: mongo-claim
      - name: mongo-config-volume
        configMap:
          name: mongo-config
      containers:
        - name: mongo-container
          image: mongo:4.0.8 # https://hub.docker.com/_/mongo/
          command:
            - mongod
            - --config
            - /data/config/mongodb.conf # config moved here
            # - "--storageEngine"
            # - wiredTiger
          ports:
            - containerPort: 27017
              protocol: TCP
          volumeMounts:
            - mountPath: "/data/db"
              name: mongo-storage
            - mountPath: "/data/config"
              name: mongo-config-volume
      restartPolicy: Always