apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
  labels:
    component: mongo
    app: auth-one
    tier: data
spec:
  ports:
  # for debug use:
  # kubectl port-forward pod-id 27017:27017
  # Connect with Robo 3T to localhost:27017
  - port: 27017
    targetPort: 27017
    protocol: TCP
  selector:
    component: mongo
  type: ClusterIP
