apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
  labels:
    component: mongo
    app: auth-one
    tier: data
spec:
  # NodePort should be used only for local development. On the cloud use a ClusterIP.
  # If you want to connect from a remote host use a Load Balanced IP only if the port is protected by a firewall.
  type: NodePort
  ports:
  - nodePort: 31105
    port: 27017
    targetPort: 27017
    protocol: TCP
  selector:
    component: mongo
